repos:
- repo: https://github.com/ambv/black
  rev: 18.9b0
  hooks:
    - id: black
      args:
        - --line-length=79
      language_version: python3
- repo: https://github.com/pre-commit/pre-commit
  rev: v1.12.0
  hooks:
    - id: validate_manifest
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-json
    - id: check-added-large-files
    - id: detect-private-key
    - id: check-docstring-first
    - id: check-merge-conflict
    - id: fix-encoding-pragma
    - id: mixed-line-ending
- repo: https://github.com/terraform-docs/terraform-docs
  rev: "v0.15.0"
  hooks:
    - id: terraform-docs-go
      args: ["markdown", "--config", "docs/terraform-docs.yml", "--escape=false", "--output-file", "README.md", "."]
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.50.0
  hooks:
    - id: terraform_fmt
    - id: terraform_validate
    - id: terraform_tfsec
    - id: terraform_tflint
      files: \.tf$
      args:
        - '--args=--only=terraform_deprecated_interpolation'
        - '--args=--only=terraform_deprecated_index'
        - '--args=--only=terraform_unused_declarations'
        - '--args=--only=terraform_comment_syntax'
        - '--args=--only=terraform_documented_outputs'
        - '--args=--only=terraform_documented_variables'
        - '--args=--only=terraform_typed_variables'
        - '--args=--only=terraform_module_pinned_source'
        - '--args=--only=terraform_naming_convention'
        - '--args=--only=terraform_required_version'
        - '--args=--only=terraform_standard_module_structure'
        - '--args=--only=terraform_workspace_remote'
